

## Prerequisite

1. `npm install`

2. install Firebase tools globally 
    -  `npm i -g firebase-tools`

3. Generate `ng` module: `ng g module <module-name>` or `ng generate module <module-name>
    - `<module-name>.module.ts`
4. Generate `ng` module with routing:`ng g module <module-name> --routing`
    - `<module-name>.module.ts`
    - `<module-name>-routing.module.ts`

5. Generate `ng` component: `ng g component <module-name>`  
    - `<module-name>.component.ts`
    - `<module-name>.component.scss`
    - `<module-name>.component.spect`
    - `<module-name>.component.html`

== Angular Basics

=== Root Routing

`app-routing.module.ts` :

Add Routes lazilly using dynamic imports

```javascript
const routes: Routes = [
  {
    path: '',
    children: [
      {
        path: 'demo',
        loadChildren: () => import('./pages/demo/demo.module').then(module => module.DemoModule) // lazy loading
      }
    ]
  }
];
```

=== Selector

Component has this decorator

```javascript
@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
```

The selector can be used to add the tags in html

`app.component.html`:

```html
<app-header></app-header>
```

=== Shared Folder

.Steps for shared feature-wise subdirectory
[options="header"]
|=======================
|Number|What      |Command| Additional Info
|1|Create Module   |`ng g module shared/parent/feature/<name>`| 
|2|Create Component   |`ng g component shared/parent/feature/<name>`| 
|3|Export in `shared/feature/<name>.module.ts`  a| 
```
import { <Name>Component } from './<name>.component' 
@NgModule({
  // ...    
  exports: [
    <Name>Component
  ]
})
```|
|4|Import and Export in `shared/parent/<name>.module.ts`  a| 
```
import { <Name>Component } from './feature/<name>.component' 
@NgModule({
  // ...    
  imports: [
    //
    <Name>Component
  ],
  exports: [
    <Name>Component
  ]
})
```|
|5|Add export for new module in `./feature/index.ts`  a| 
```
  // ...    
  export * from './feature/<name>.module';
})
```|

|=======================



=== Models Folder


=== Backend 

> Firebase DB

=== Frontend

> Fetching data from backend for SELECT, AUTOCOMPLETE and CHECKBOXES
attribute

It had the following TS `interfaces`

1. control-item

2. icon

3. item


