ports:
  - port: 4200
    onOpen: open-preview

tasks:
  - init: npm install -g @angular/cli
  - init: npm install
    command: >
      export NG_CLI_ANALYTICS=off &&
      cd /course-app && 
      npm run start

github:
  prebuilds:
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true